print(str("Hello"))
print(int(42))
print(float(3.14))
print(bool(True))
print(type(str("Hello")))
print(type(int(42)))
print(type(float(3.14)))
print(type(bool(True)))
print(isinstance(str("Hello")))
print(isinstance(bool(True)))
print(isinstance(float(3.14)))
print(isinstance(int(42)))
print(number=str("Hello"))
print(number=int(42))
print(number=float(3.14))
print(number=bool(True))
print(Hello  = number )
print(int42 = number)
print(boolTrue = number)
print( float 3.14=number)
print(int(3.14))
 